// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *HumanUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InstanceMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MachineUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PersonalAccessToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectGrantMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserGrant) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserMetadata) Hub() {}
