apiVersion: machine.zitadel.crossplane.io/v1alpha1
kind: MachineKey
metadata:
  annotations:
    meta.upbound.io/example-id: machine/v1alpha1/machinekey
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    expirationDate: "2519-04-01T08:45:00Z"
    keyType: KEY_TYPE_JSON
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_machine_user
