apiVersion: idp.zitadel.crossplane.io/v1alpha1
kind: IdpGithub
metadata:
  annotations:
    meta.upbound.io/example-id: idp/v1alpha1/idpgithub
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    clientId: 86a165...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    name: GitHub
    scopes:
    - openid
    - profile
    - email
