apiVersion: idp.zitadel.crossplane.io/v1alpha1
kind: IdpGithubEs
metadata:
  annotations:
    meta.upbound.io/example-id: idp/v1alpha1/idpgithubes
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    authorizationEndpoint: https://auth.endpoint
    clientId: 86a165...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    name: GitHub Enterprise Server
    scopes:
    - openid
    - profile
    - email
    tokenEndpoint: https://token.endpoint
    userEndpoint: https://user.endpoint
