apiVersion: idp.zitadel.crossplane.io/v1alpha1
kind: IdpGitlabSelfHosted
metadata:
  annotations:
    meta.upbound.io/example-id: idp/v1alpha1/idpgitlabselfhosted
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    clientId: 15765e...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    issuer: https://my.issuer
    name: GitLab Self Hosted
    scopes:
    - openid
    - profile
    - email
