apiVersion: idp.zitadel.crossplane.io/v1alpha1
kind: OrgIdpOidc
metadata:
  annotations:
    meta.upbound.io/example-id: idp/v1alpha1/orgidpoidc
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    clientId: a_client_id
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isIdTokenMapping: true
    isLinkingAllowed: false
    issuer: https://example.com
    name: My Generic OIDC IDP
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    scopes:
    - openid
    - profile
    - email
