apiVersion: idp.zitadel.crossplane.io/v1alpha1
kind: OrgIdpAzureAd
metadata:
  annotations:
    meta.upbound.io/example-id: idp/v1alpha1/orgidpazuread
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    clientId: 9065bfc8-a08a...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    emailVerified: true
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    name: Azure AD
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    scopes:
    - openid
    - profile
    - email
    - User.Read
    tenantType: AZURE_AD_TENANT_TYPE_ORGANISATIONS
