apiVersion: idp.zitadel.crossplane.io/v1alpha1
kind: OrgIdpGoogle
metadata:
  annotations:
    meta.upbound.io/example-id: idp/v1alpha1/orgidpgoogle
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    clientId: 182902...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    name: Google
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    scopes:
    - openid
    - profile
    - email
