apiVersion: idp.zitadel.crossplane.io/v1alpha1
kind: OrgIdpLdap
metadata:
  annotations:
    meta.upbound.io/example-id: idp/v1alpha1/orgidpldap
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    baseDn: dc=example,dc=com
    bindDn: cn=admin,dc=example,dc=com
    bindPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    firstNameAttribute: firstname
    idAttribute: uid
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    lastNameAttribute: lastname
    name: LDAP
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    servers:
    - ldaps://my.primary.server:389
    - ldaps://my.secondary.server:389
    startTls: false
    timeout: 10s
    userBase: dn
    userFilters:
    - uid
    - email
    userObjectClasses:
    - inetOrgPerson
