//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDomainPolicy) DeepCopyInto(out *DefaultDomainPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDomainPolicy.
func (in *DefaultDomainPolicy) DeepCopy() *DefaultDomainPolicy {
	if in == nil {
		return nil
	}
	out := new(DefaultDomainPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultDomainPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDomainPolicyInitParameters) DeepCopyInto(out *DefaultDomainPolicyInitParameters) {
	*out = *in
	if in.SMTPSenderAddressMatchesInstanceDomain != nil {
		in, out := &in.SMTPSenderAddressMatchesInstanceDomain, &out.SMTPSenderAddressMatchesInstanceDomain
		*out = new(bool)
		**out = **in
	}
	if in.UserLoginMustBeDomain != nil {
		in, out := &in.UserLoginMustBeDomain, &out.UserLoginMustBeDomain
		*out = new(bool)
		**out = **in
	}
	if in.ValidateOrgDomains != nil {
		in, out := &in.ValidateOrgDomains, &out.ValidateOrgDomains
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDomainPolicyInitParameters.
func (in *DefaultDomainPolicyInitParameters) DeepCopy() *DefaultDomainPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultDomainPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDomainPolicyList) DeepCopyInto(out *DefaultDomainPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DefaultDomainPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDomainPolicyList.
func (in *DefaultDomainPolicyList) DeepCopy() *DefaultDomainPolicyList {
	if in == nil {
		return nil
	}
	out := new(DefaultDomainPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultDomainPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDomainPolicyObservation) DeepCopyInto(out *DefaultDomainPolicyObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.SMTPSenderAddressMatchesInstanceDomain != nil {
		in, out := &in.SMTPSenderAddressMatchesInstanceDomain, &out.SMTPSenderAddressMatchesInstanceDomain
		*out = new(bool)
		**out = **in
	}
	if in.UserLoginMustBeDomain != nil {
		in, out := &in.UserLoginMustBeDomain, &out.UserLoginMustBeDomain
		*out = new(bool)
		**out = **in
	}
	if in.ValidateOrgDomains != nil {
		in, out := &in.ValidateOrgDomains, &out.ValidateOrgDomains
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDomainPolicyObservation.
func (in *DefaultDomainPolicyObservation) DeepCopy() *DefaultDomainPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultDomainPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDomainPolicyParameters) DeepCopyInto(out *DefaultDomainPolicyParameters) {
	*out = *in
	if in.SMTPSenderAddressMatchesInstanceDomain != nil {
		in, out := &in.SMTPSenderAddressMatchesInstanceDomain, &out.SMTPSenderAddressMatchesInstanceDomain
		*out = new(bool)
		**out = **in
	}
	if in.UserLoginMustBeDomain != nil {
		in, out := &in.UserLoginMustBeDomain, &out.UserLoginMustBeDomain
		*out = new(bool)
		**out = **in
	}
	if in.ValidateOrgDomains != nil {
		in, out := &in.ValidateOrgDomains, &out.ValidateOrgDomains
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDomainPolicyParameters.
func (in *DefaultDomainPolicyParameters) DeepCopy() *DefaultDomainPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultDomainPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDomainPolicySpec) DeepCopyInto(out *DefaultDomainPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDomainPolicySpec.
func (in *DefaultDomainPolicySpec) DeepCopy() *DefaultDomainPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DefaultDomainPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDomainPolicyStatus) DeepCopyInto(out *DefaultDomainPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDomainPolicyStatus.
func (in *DefaultDomainPolicyStatus) DeepCopy() *DefaultDomainPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DefaultDomainPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLabelPolicy) DeepCopyInto(out *DefaultLabelPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLabelPolicy.
func (in *DefaultLabelPolicy) DeepCopy() *DefaultLabelPolicy {
	if in == nil {
		return nil
	}
	out := new(DefaultLabelPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultLabelPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLabelPolicyInitParameters) DeepCopyInto(out *DefaultLabelPolicyInitParameters) {
	*out = *in
	if in.BackgroundColor != nil {
		in, out := &in.BackgroundColor, &out.BackgroundColor
		*out = new(string)
		**out = **in
	}
	if in.BackgroundColorDark != nil {
		in, out := &in.BackgroundColorDark, &out.BackgroundColorDark
		*out = new(string)
		**out = **in
	}
	if in.DisableWatermark != nil {
		in, out := &in.DisableWatermark, &out.DisableWatermark
		*out = new(bool)
		**out = **in
	}
	if in.FontColor != nil {
		in, out := &in.FontColor, &out.FontColor
		*out = new(string)
		**out = **in
	}
	if in.FontColorDark != nil {
		in, out := &in.FontColorDark, &out.FontColorDark
		*out = new(string)
		**out = **in
	}
	if in.FontHash != nil {
		in, out := &in.FontHash, &out.FontHash
		*out = new(string)
		**out = **in
	}
	if in.FontPath != nil {
		in, out := &in.FontPath, &out.FontPath
		*out = new(string)
		**out = **in
	}
	if in.HideLoginNameSuffix != nil {
		in, out := &in.HideLoginNameSuffix, &out.HideLoginNameSuffix
		*out = new(bool)
		**out = **in
	}
	if in.IconDarkHash != nil {
		in, out := &in.IconDarkHash, &out.IconDarkHash
		*out = new(string)
		**out = **in
	}
	if in.IconDarkPath != nil {
		in, out := &in.IconDarkPath, &out.IconDarkPath
		*out = new(string)
		**out = **in
	}
	if in.IconHash != nil {
		in, out := &in.IconHash, &out.IconHash
		*out = new(string)
		**out = **in
	}
	if in.IconPath != nil {
		in, out := &in.IconPath, &out.IconPath
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkHash != nil {
		in, out := &in.LogoDarkHash, &out.LogoDarkHash
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkPath != nil {
		in, out := &in.LogoDarkPath, &out.LogoDarkPath
		*out = new(string)
		**out = **in
	}
	if in.LogoHash != nil {
		in, out := &in.LogoHash, &out.LogoHash
		*out = new(string)
		**out = **in
	}
	if in.LogoPath != nil {
		in, out := &in.LogoPath, &out.LogoPath
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColor != nil {
		in, out := &in.PrimaryColor, &out.PrimaryColor
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColorDark != nil {
		in, out := &in.PrimaryColorDark, &out.PrimaryColorDark
		*out = new(string)
		**out = **in
	}
	if in.SetActive != nil {
		in, out := &in.SetActive, &out.SetActive
		*out = new(bool)
		**out = **in
	}
	if in.ThemeMode != nil {
		in, out := &in.ThemeMode, &out.ThemeMode
		*out = new(string)
		**out = **in
	}
	if in.WarnColor != nil {
		in, out := &in.WarnColor, &out.WarnColor
		*out = new(string)
		**out = **in
	}
	if in.WarnColorDark != nil {
		in, out := &in.WarnColorDark, &out.WarnColorDark
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLabelPolicyInitParameters.
func (in *DefaultLabelPolicyInitParameters) DeepCopy() *DefaultLabelPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultLabelPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLabelPolicyList) DeepCopyInto(out *DefaultLabelPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DefaultLabelPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLabelPolicyList.
func (in *DefaultLabelPolicyList) DeepCopy() *DefaultLabelPolicyList {
	if in == nil {
		return nil
	}
	out := new(DefaultLabelPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultLabelPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLabelPolicyObservation) DeepCopyInto(out *DefaultLabelPolicyObservation) {
	*out = *in
	if in.BackgroundColor != nil {
		in, out := &in.BackgroundColor, &out.BackgroundColor
		*out = new(string)
		**out = **in
	}
	if in.BackgroundColorDark != nil {
		in, out := &in.BackgroundColorDark, &out.BackgroundColorDark
		*out = new(string)
		**out = **in
	}
	if in.DisableWatermark != nil {
		in, out := &in.DisableWatermark, &out.DisableWatermark
		*out = new(bool)
		**out = **in
	}
	if in.FontColor != nil {
		in, out := &in.FontColor, &out.FontColor
		*out = new(string)
		**out = **in
	}
	if in.FontColorDark != nil {
		in, out := &in.FontColorDark, &out.FontColorDark
		*out = new(string)
		**out = **in
	}
	if in.FontHash != nil {
		in, out := &in.FontHash, &out.FontHash
		*out = new(string)
		**out = **in
	}
	if in.FontPath != nil {
		in, out := &in.FontPath, &out.FontPath
		*out = new(string)
		**out = **in
	}
	if in.FontURL != nil {
		in, out := &in.FontURL, &out.FontURL
		*out = new(string)
		**out = **in
	}
	if in.HideLoginNameSuffix != nil {
		in, out := &in.HideLoginNameSuffix, &out.HideLoginNameSuffix
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IconDarkHash != nil {
		in, out := &in.IconDarkHash, &out.IconDarkHash
		*out = new(string)
		**out = **in
	}
	if in.IconDarkPath != nil {
		in, out := &in.IconDarkPath, &out.IconDarkPath
		*out = new(string)
		**out = **in
	}
	if in.IconHash != nil {
		in, out := &in.IconHash, &out.IconHash
		*out = new(string)
		**out = **in
	}
	if in.IconPath != nil {
		in, out := &in.IconPath, &out.IconPath
		*out = new(string)
		**out = **in
	}
	if in.IconURL != nil {
		in, out := &in.IconURL, &out.IconURL
		*out = new(string)
		**out = **in
	}
	if in.IconURLDark != nil {
		in, out := &in.IconURLDark, &out.IconURLDark
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkHash != nil {
		in, out := &in.LogoDarkHash, &out.LogoDarkHash
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkPath != nil {
		in, out := &in.LogoDarkPath, &out.LogoDarkPath
		*out = new(string)
		**out = **in
	}
	if in.LogoHash != nil {
		in, out := &in.LogoHash, &out.LogoHash
		*out = new(string)
		**out = **in
	}
	if in.LogoPath != nil {
		in, out := &in.LogoPath, &out.LogoPath
		*out = new(string)
		**out = **in
	}
	if in.LogoURL != nil {
		in, out := &in.LogoURL, &out.LogoURL
		*out = new(string)
		**out = **in
	}
	if in.LogoURLDark != nil {
		in, out := &in.LogoURLDark, &out.LogoURLDark
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColor != nil {
		in, out := &in.PrimaryColor, &out.PrimaryColor
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColorDark != nil {
		in, out := &in.PrimaryColorDark, &out.PrimaryColorDark
		*out = new(string)
		**out = **in
	}
	if in.SetActive != nil {
		in, out := &in.SetActive, &out.SetActive
		*out = new(bool)
		**out = **in
	}
	if in.ThemeMode != nil {
		in, out := &in.ThemeMode, &out.ThemeMode
		*out = new(string)
		**out = **in
	}
	if in.WarnColor != nil {
		in, out := &in.WarnColor, &out.WarnColor
		*out = new(string)
		**out = **in
	}
	if in.WarnColorDark != nil {
		in, out := &in.WarnColorDark, &out.WarnColorDark
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLabelPolicyObservation.
func (in *DefaultLabelPolicyObservation) DeepCopy() *DefaultLabelPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultLabelPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLabelPolicyParameters) DeepCopyInto(out *DefaultLabelPolicyParameters) {
	*out = *in
	if in.BackgroundColor != nil {
		in, out := &in.BackgroundColor, &out.BackgroundColor
		*out = new(string)
		**out = **in
	}
	if in.BackgroundColorDark != nil {
		in, out := &in.BackgroundColorDark, &out.BackgroundColorDark
		*out = new(string)
		**out = **in
	}
	if in.DisableWatermark != nil {
		in, out := &in.DisableWatermark, &out.DisableWatermark
		*out = new(bool)
		**out = **in
	}
	if in.FontColor != nil {
		in, out := &in.FontColor, &out.FontColor
		*out = new(string)
		**out = **in
	}
	if in.FontColorDark != nil {
		in, out := &in.FontColorDark, &out.FontColorDark
		*out = new(string)
		**out = **in
	}
	if in.FontHash != nil {
		in, out := &in.FontHash, &out.FontHash
		*out = new(string)
		**out = **in
	}
	if in.FontPath != nil {
		in, out := &in.FontPath, &out.FontPath
		*out = new(string)
		**out = **in
	}
	if in.HideLoginNameSuffix != nil {
		in, out := &in.HideLoginNameSuffix, &out.HideLoginNameSuffix
		*out = new(bool)
		**out = **in
	}
	if in.IconDarkHash != nil {
		in, out := &in.IconDarkHash, &out.IconDarkHash
		*out = new(string)
		**out = **in
	}
	if in.IconDarkPath != nil {
		in, out := &in.IconDarkPath, &out.IconDarkPath
		*out = new(string)
		**out = **in
	}
	if in.IconHash != nil {
		in, out := &in.IconHash, &out.IconHash
		*out = new(string)
		**out = **in
	}
	if in.IconPath != nil {
		in, out := &in.IconPath, &out.IconPath
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkHash != nil {
		in, out := &in.LogoDarkHash, &out.LogoDarkHash
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkPath != nil {
		in, out := &in.LogoDarkPath, &out.LogoDarkPath
		*out = new(string)
		**out = **in
	}
	if in.LogoHash != nil {
		in, out := &in.LogoHash, &out.LogoHash
		*out = new(string)
		**out = **in
	}
	if in.LogoPath != nil {
		in, out := &in.LogoPath, &out.LogoPath
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColor != nil {
		in, out := &in.PrimaryColor, &out.PrimaryColor
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColorDark != nil {
		in, out := &in.PrimaryColorDark, &out.PrimaryColorDark
		*out = new(string)
		**out = **in
	}
	if in.SetActive != nil {
		in, out := &in.SetActive, &out.SetActive
		*out = new(bool)
		**out = **in
	}
	if in.ThemeMode != nil {
		in, out := &in.ThemeMode, &out.ThemeMode
		*out = new(string)
		**out = **in
	}
	if in.WarnColor != nil {
		in, out := &in.WarnColor, &out.WarnColor
		*out = new(string)
		**out = **in
	}
	if in.WarnColorDark != nil {
		in, out := &in.WarnColorDark, &out.WarnColorDark
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLabelPolicyParameters.
func (in *DefaultLabelPolicyParameters) DeepCopy() *DefaultLabelPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultLabelPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLabelPolicySpec) DeepCopyInto(out *DefaultLabelPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLabelPolicySpec.
func (in *DefaultLabelPolicySpec) DeepCopy() *DefaultLabelPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DefaultLabelPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLabelPolicyStatus) DeepCopyInto(out *DefaultLabelPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLabelPolicyStatus.
func (in *DefaultLabelPolicyStatus) DeepCopy() *DefaultLabelPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DefaultLabelPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLockoutPolicy) DeepCopyInto(out *DefaultLockoutPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLockoutPolicy.
func (in *DefaultLockoutPolicy) DeepCopy() *DefaultLockoutPolicy {
	if in == nil {
		return nil
	}
	out := new(DefaultLockoutPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultLockoutPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLockoutPolicyInitParameters) DeepCopyInto(out *DefaultLockoutPolicyInitParameters) {
	*out = *in
	if in.MaxPasswordAttempts != nil {
		in, out := &in.MaxPasswordAttempts, &out.MaxPasswordAttempts
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLockoutPolicyInitParameters.
func (in *DefaultLockoutPolicyInitParameters) DeepCopy() *DefaultLockoutPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultLockoutPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLockoutPolicyList) DeepCopyInto(out *DefaultLockoutPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DefaultLockoutPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLockoutPolicyList.
func (in *DefaultLockoutPolicyList) DeepCopy() *DefaultLockoutPolicyList {
	if in == nil {
		return nil
	}
	out := new(DefaultLockoutPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultLockoutPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLockoutPolicyObservation) DeepCopyInto(out *DefaultLockoutPolicyObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxPasswordAttempts != nil {
		in, out := &in.MaxPasswordAttempts, &out.MaxPasswordAttempts
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLockoutPolicyObservation.
func (in *DefaultLockoutPolicyObservation) DeepCopy() *DefaultLockoutPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultLockoutPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLockoutPolicyParameters) DeepCopyInto(out *DefaultLockoutPolicyParameters) {
	*out = *in
	if in.MaxPasswordAttempts != nil {
		in, out := &in.MaxPasswordAttempts, &out.MaxPasswordAttempts
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLockoutPolicyParameters.
func (in *DefaultLockoutPolicyParameters) DeepCopy() *DefaultLockoutPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultLockoutPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLockoutPolicySpec) DeepCopyInto(out *DefaultLockoutPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLockoutPolicySpec.
func (in *DefaultLockoutPolicySpec) DeepCopy() *DefaultLockoutPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DefaultLockoutPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLockoutPolicyStatus) DeepCopyInto(out *DefaultLockoutPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLockoutPolicyStatus.
func (in *DefaultLockoutPolicyStatus) DeepCopy() *DefaultLockoutPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DefaultLockoutPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLoginPolicy) DeepCopyInto(out *DefaultLoginPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLoginPolicy.
func (in *DefaultLoginPolicy) DeepCopy() *DefaultLoginPolicy {
	if in == nil {
		return nil
	}
	out := new(DefaultLoginPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultLoginPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLoginPolicyInitParameters) DeepCopyInto(out *DefaultLoginPolicyInitParameters) {
	*out = *in
	if in.AllowDomainDiscovery != nil {
		in, out := &in.AllowDomainDiscovery, &out.AllowDomainDiscovery
		*out = new(bool)
		**out = **in
	}
	if in.AllowExternalIdp != nil {
		in, out := &in.AllowExternalIdp, &out.AllowExternalIdp
		*out = new(bool)
		**out = **in
	}
	if in.AllowRegister != nil {
		in, out := &in.AllowRegister, &out.AllowRegister
		*out = new(bool)
		**out = **in
	}
	if in.DefaultRedirectURI != nil {
		in, out := &in.DefaultRedirectURI, &out.DefaultRedirectURI
		*out = new(string)
		**out = **in
	}
	if in.DisableLoginWithEmail != nil {
		in, out := &in.DisableLoginWithEmail, &out.DisableLoginWithEmail
		*out = new(bool)
		**out = **in
	}
	if in.DisableLoginWithPhone != nil {
		in, out := &in.DisableLoginWithPhone, &out.DisableLoginWithPhone
		*out = new(bool)
		**out = **in
	}
	if in.ExternalLoginCheckLifetime != nil {
		in, out := &in.ExternalLoginCheckLifetime, &out.ExternalLoginCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.ForceMfa != nil {
		in, out := &in.ForceMfa, &out.ForceMfa
		*out = new(bool)
		**out = **in
	}
	if in.ForceMfaLocalOnly != nil {
		in, out := &in.ForceMfaLocalOnly, &out.ForceMfaLocalOnly
		*out = new(bool)
		**out = **in
	}
	if in.HidePasswordReset != nil {
		in, out := &in.HidePasswordReset, &out.HidePasswordReset
		*out = new(bool)
		**out = **in
	}
	if in.Idps != nil {
		in, out := &in.Idps, &out.Idps
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IgnoreUnknownUsernames != nil {
		in, out := &in.IgnoreUnknownUsernames, &out.IgnoreUnknownUsernames
		*out = new(bool)
		**out = **in
	}
	if in.MfaInitSkipLifetime != nil {
		in, out := &in.MfaInitSkipLifetime, &out.MfaInitSkipLifetime
		*out = new(string)
		**out = **in
	}
	if in.MultiFactorCheckLifetime != nil {
		in, out := &in.MultiFactorCheckLifetime, &out.MultiFactorCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.MultiFactors != nil {
		in, out := &in.MultiFactors, &out.MultiFactors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PasswordCheckLifetime != nil {
		in, out := &in.PasswordCheckLifetime, &out.PasswordCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.PasswordlessType != nil {
		in, out := &in.PasswordlessType, &out.PasswordlessType
		*out = new(string)
		**out = **in
	}
	if in.SecondFactorCheckLifetime != nil {
		in, out := &in.SecondFactorCheckLifetime, &out.SecondFactorCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.SecondFactors != nil {
		in, out := &in.SecondFactors, &out.SecondFactors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserLogin != nil {
		in, out := &in.UserLogin, &out.UserLogin
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLoginPolicyInitParameters.
func (in *DefaultLoginPolicyInitParameters) DeepCopy() *DefaultLoginPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultLoginPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLoginPolicyList) DeepCopyInto(out *DefaultLoginPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DefaultLoginPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLoginPolicyList.
func (in *DefaultLoginPolicyList) DeepCopy() *DefaultLoginPolicyList {
	if in == nil {
		return nil
	}
	out := new(DefaultLoginPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultLoginPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLoginPolicyObservation) DeepCopyInto(out *DefaultLoginPolicyObservation) {
	*out = *in
	if in.AllowDomainDiscovery != nil {
		in, out := &in.AllowDomainDiscovery, &out.AllowDomainDiscovery
		*out = new(bool)
		**out = **in
	}
	if in.AllowExternalIdp != nil {
		in, out := &in.AllowExternalIdp, &out.AllowExternalIdp
		*out = new(bool)
		**out = **in
	}
	if in.AllowRegister != nil {
		in, out := &in.AllowRegister, &out.AllowRegister
		*out = new(bool)
		**out = **in
	}
	if in.DefaultRedirectURI != nil {
		in, out := &in.DefaultRedirectURI, &out.DefaultRedirectURI
		*out = new(string)
		**out = **in
	}
	if in.DisableLoginWithEmail != nil {
		in, out := &in.DisableLoginWithEmail, &out.DisableLoginWithEmail
		*out = new(bool)
		**out = **in
	}
	if in.DisableLoginWithPhone != nil {
		in, out := &in.DisableLoginWithPhone, &out.DisableLoginWithPhone
		*out = new(bool)
		**out = **in
	}
	if in.ExternalLoginCheckLifetime != nil {
		in, out := &in.ExternalLoginCheckLifetime, &out.ExternalLoginCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.ForceMfa != nil {
		in, out := &in.ForceMfa, &out.ForceMfa
		*out = new(bool)
		**out = **in
	}
	if in.ForceMfaLocalOnly != nil {
		in, out := &in.ForceMfaLocalOnly, &out.ForceMfaLocalOnly
		*out = new(bool)
		**out = **in
	}
	if in.HidePasswordReset != nil {
		in, out := &in.HidePasswordReset, &out.HidePasswordReset
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Idps != nil {
		in, out := &in.Idps, &out.Idps
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IgnoreUnknownUsernames != nil {
		in, out := &in.IgnoreUnknownUsernames, &out.IgnoreUnknownUsernames
		*out = new(bool)
		**out = **in
	}
	if in.MfaInitSkipLifetime != nil {
		in, out := &in.MfaInitSkipLifetime, &out.MfaInitSkipLifetime
		*out = new(string)
		**out = **in
	}
	if in.MultiFactorCheckLifetime != nil {
		in, out := &in.MultiFactorCheckLifetime, &out.MultiFactorCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.MultiFactors != nil {
		in, out := &in.MultiFactors, &out.MultiFactors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PasswordCheckLifetime != nil {
		in, out := &in.PasswordCheckLifetime, &out.PasswordCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.PasswordlessType != nil {
		in, out := &in.PasswordlessType, &out.PasswordlessType
		*out = new(string)
		**out = **in
	}
	if in.SecondFactorCheckLifetime != nil {
		in, out := &in.SecondFactorCheckLifetime, &out.SecondFactorCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.SecondFactors != nil {
		in, out := &in.SecondFactors, &out.SecondFactors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserLogin != nil {
		in, out := &in.UserLogin, &out.UserLogin
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLoginPolicyObservation.
func (in *DefaultLoginPolicyObservation) DeepCopy() *DefaultLoginPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultLoginPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLoginPolicyParameters) DeepCopyInto(out *DefaultLoginPolicyParameters) {
	*out = *in
	if in.AllowDomainDiscovery != nil {
		in, out := &in.AllowDomainDiscovery, &out.AllowDomainDiscovery
		*out = new(bool)
		**out = **in
	}
	if in.AllowExternalIdp != nil {
		in, out := &in.AllowExternalIdp, &out.AllowExternalIdp
		*out = new(bool)
		**out = **in
	}
	if in.AllowRegister != nil {
		in, out := &in.AllowRegister, &out.AllowRegister
		*out = new(bool)
		**out = **in
	}
	if in.DefaultRedirectURI != nil {
		in, out := &in.DefaultRedirectURI, &out.DefaultRedirectURI
		*out = new(string)
		**out = **in
	}
	if in.DisableLoginWithEmail != nil {
		in, out := &in.DisableLoginWithEmail, &out.DisableLoginWithEmail
		*out = new(bool)
		**out = **in
	}
	if in.DisableLoginWithPhone != nil {
		in, out := &in.DisableLoginWithPhone, &out.DisableLoginWithPhone
		*out = new(bool)
		**out = **in
	}
	if in.ExternalLoginCheckLifetime != nil {
		in, out := &in.ExternalLoginCheckLifetime, &out.ExternalLoginCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.ForceMfa != nil {
		in, out := &in.ForceMfa, &out.ForceMfa
		*out = new(bool)
		**out = **in
	}
	if in.ForceMfaLocalOnly != nil {
		in, out := &in.ForceMfaLocalOnly, &out.ForceMfaLocalOnly
		*out = new(bool)
		**out = **in
	}
	if in.HidePasswordReset != nil {
		in, out := &in.HidePasswordReset, &out.HidePasswordReset
		*out = new(bool)
		**out = **in
	}
	if in.Idps != nil {
		in, out := &in.Idps, &out.Idps
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IgnoreUnknownUsernames != nil {
		in, out := &in.IgnoreUnknownUsernames, &out.IgnoreUnknownUsernames
		*out = new(bool)
		**out = **in
	}
	if in.MfaInitSkipLifetime != nil {
		in, out := &in.MfaInitSkipLifetime, &out.MfaInitSkipLifetime
		*out = new(string)
		**out = **in
	}
	if in.MultiFactorCheckLifetime != nil {
		in, out := &in.MultiFactorCheckLifetime, &out.MultiFactorCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.MultiFactors != nil {
		in, out := &in.MultiFactors, &out.MultiFactors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PasswordCheckLifetime != nil {
		in, out := &in.PasswordCheckLifetime, &out.PasswordCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.PasswordlessType != nil {
		in, out := &in.PasswordlessType, &out.PasswordlessType
		*out = new(string)
		**out = **in
	}
	if in.SecondFactorCheckLifetime != nil {
		in, out := &in.SecondFactorCheckLifetime, &out.SecondFactorCheckLifetime
		*out = new(string)
		**out = **in
	}
	if in.SecondFactors != nil {
		in, out := &in.SecondFactors, &out.SecondFactors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserLogin != nil {
		in, out := &in.UserLogin, &out.UserLogin
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLoginPolicyParameters.
func (in *DefaultLoginPolicyParameters) DeepCopy() *DefaultLoginPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultLoginPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLoginPolicySpec) DeepCopyInto(out *DefaultLoginPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLoginPolicySpec.
func (in *DefaultLoginPolicySpec) DeepCopy() *DefaultLoginPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DefaultLoginPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultLoginPolicyStatus) DeepCopyInto(out *DefaultLoginPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultLoginPolicyStatus.
func (in *DefaultLoginPolicyStatus) DeepCopy() *DefaultLoginPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DefaultLoginPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultNotificationPolicy) DeepCopyInto(out *DefaultNotificationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultNotificationPolicy.
func (in *DefaultNotificationPolicy) DeepCopy() *DefaultNotificationPolicy {
	if in == nil {
		return nil
	}
	out := new(DefaultNotificationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultNotificationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultNotificationPolicyInitParameters) DeepCopyInto(out *DefaultNotificationPolicyInitParameters) {
	*out = *in
	if in.PasswordChange != nil {
		in, out := &in.PasswordChange, &out.PasswordChange
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultNotificationPolicyInitParameters.
func (in *DefaultNotificationPolicyInitParameters) DeepCopy() *DefaultNotificationPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultNotificationPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultNotificationPolicyList) DeepCopyInto(out *DefaultNotificationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DefaultNotificationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultNotificationPolicyList.
func (in *DefaultNotificationPolicyList) DeepCopy() *DefaultNotificationPolicyList {
	if in == nil {
		return nil
	}
	out := new(DefaultNotificationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultNotificationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultNotificationPolicyObservation) DeepCopyInto(out *DefaultNotificationPolicyObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PasswordChange != nil {
		in, out := &in.PasswordChange, &out.PasswordChange
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultNotificationPolicyObservation.
func (in *DefaultNotificationPolicyObservation) DeepCopy() *DefaultNotificationPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultNotificationPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultNotificationPolicyParameters) DeepCopyInto(out *DefaultNotificationPolicyParameters) {
	*out = *in
	if in.PasswordChange != nil {
		in, out := &in.PasswordChange, &out.PasswordChange
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultNotificationPolicyParameters.
func (in *DefaultNotificationPolicyParameters) DeepCopy() *DefaultNotificationPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultNotificationPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultNotificationPolicySpec) DeepCopyInto(out *DefaultNotificationPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultNotificationPolicySpec.
func (in *DefaultNotificationPolicySpec) DeepCopy() *DefaultNotificationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DefaultNotificationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultNotificationPolicyStatus) DeepCopyInto(out *DefaultNotificationPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultNotificationPolicyStatus.
func (in *DefaultNotificationPolicyStatus) DeepCopy() *DefaultNotificationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DefaultNotificationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultOIDCSettings) DeepCopyInto(out *DefaultOIDCSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultOIDCSettings.
func (in *DefaultOIDCSettings) DeepCopy() *DefaultOIDCSettings {
	if in == nil {
		return nil
	}
	out := new(DefaultOIDCSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultOIDCSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultOIDCSettingsInitParameters) DeepCopyInto(out *DefaultOIDCSettingsInitParameters) {
	*out = *in
	if in.AccessTokenLifetime != nil {
		in, out := &in.AccessTokenLifetime, &out.AccessTokenLifetime
		*out = new(string)
		**out = **in
	}
	if in.IDTokenLifetime != nil {
		in, out := &in.IDTokenLifetime, &out.IDTokenLifetime
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenExpiration != nil {
		in, out := &in.RefreshTokenExpiration, &out.RefreshTokenExpiration
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenIdleExpiration != nil {
		in, out := &in.RefreshTokenIdleExpiration, &out.RefreshTokenIdleExpiration
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultOIDCSettingsInitParameters.
func (in *DefaultOIDCSettingsInitParameters) DeepCopy() *DefaultOIDCSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultOIDCSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultOIDCSettingsList) DeepCopyInto(out *DefaultOIDCSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DefaultOIDCSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultOIDCSettingsList.
func (in *DefaultOIDCSettingsList) DeepCopy() *DefaultOIDCSettingsList {
	if in == nil {
		return nil
	}
	out := new(DefaultOIDCSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultOIDCSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultOIDCSettingsObservation) DeepCopyInto(out *DefaultOIDCSettingsObservation) {
	*out = *in
	if in.AccessTokenLifetime != nil {
		in, out := &in.AccessTokenLifetime, &out.AccessTokenLifetime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IDTokenLifetime != nil {
		in, out := &in.IDTokenLifetime, &out.IDTokenLifetime
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenExpiration != nil {
		in, out := &in.RefreshTokenExpiration, &out.RefreshTokenExpiration
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenIdleExpiration != nil {
		in, out := &in.RefreshTokenIdleExpiration, &out.RefreshTokenIdleExpiration
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultOIDCSettingsObservation.
func (in *DefaultOIDCSettingsObservation) DeepCopy() *DefaultOIDCSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultOIDCSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultOIDCSettingsParameters) DeepCopyInto(out *DefaultOIDCSettingsParameters) {
	*out = *in
	if in.AccessTokenLifetime != nil {
		in, out := &in.AccessTokenLifetime, &out.AccessTokenLifetime
		*out = new(string)
		**out = **in
	}
	if in.IDTokenLifetime != nil {
		in, out := &in.IDTokenLifetime, &out.IDTokenLifetime
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenExpiration != nil {
		in, out := &in.RefreshTokenExpiration, &out.RefreshTokenExpiration
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenIdleExpiration != nil {
		in, out := &in.RefreshTokenIdleExpiration, &out.RefreshTokenIdleExpiration
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultOIDCSettingsParameters.
func (in *DefaultOIDCSettingsParameters) DeepCopy() *DefaultOIDCSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultOIDCSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultOIDCSettingsSpec) DeepCopyInto(out *DefaultOIDCSettingsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultOIDCSettingsSpec.
func (in *DefaultOIDCSettingsSpec) DeepCopy() *DefaultOIDCSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(DefaultOIDCSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultOIDCSettingsStatus) DeepCopyInto(out *DefaultOIDCSettingsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultOIDCSettingsStatus.
func (in *DefaultOIDCSettingsStatus) DeepCopy() *DefaultOIDCSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(DefaultOIDCSettingsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPrivacyPolicy) DeepCopyInto(out *DefaultPrivacyPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPrivacyPolicy.
func (in *DefaultPrivacyPolicy) DeepCopy() *DefaultPrivacyPolicy {
	if in == nil {
		return nil
	}
	out := new(DefaultPrivacyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultPrivacyPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPrivacyPolicyInitParameters) DeepCopyInto(out *DefaultPrivacyPolicyInitParameters) {
	*out = *in
	if in.HelpLink != nil {
		in, out := &in.HelpLink, &out.HelpLink
		*out = new(string)
		**out = **in
	}
	if in.PrivacyLink != nil {
		in, out := &in.PrivacyLink, &out.PrivacyLink
		*out = new(string)
		**out = **in
	}
	if in.SupportEmail != nil {
		in, out := &in.SupportEmail, &out.SupportEmail
		*out = new(string)
		**out = **in
	}
	if in.TosLink != nil {
		in, out := &in.TosLink, &out.TosLink
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPrivacyPolicyInitParameters.
func (in *DefaultPrivacyPolicyInitParameters) DeepCopy() *DefaultPrivacyPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultPrivacyPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPrivacyPolicyList) DeepCopyInto(out *DefaultPrivacyPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DefaultPrivacyPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPrivacyPolicyList.
func (in *DefaultPrivacyPolicyList) DeepCopy() *DefaultPrivacyPolicyList {
	if in == nil {
		return nil
	}
	out := new(DefaultPrivacyPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultPrivacyPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPrivacyPolicyObservation) DeepCopyInto(out *DefaultPrivacyPolicyObservation) {
	*out = *in
	if in.HelpLink != nil {
		in, out := &in.HelpLink, &out.HelpLink
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PrivacyLink != nil {
		in, out := &in.PrivacyLink, &out.PrivacyLink
		*out = new(string)
		**out = **in
	}
	if in.SupportEmail != nil {
		in, out := &in.SupportEmail, &out.SupportEmail
		*out = new(string)
		**out = **in
	}
	if in.TosLink != nil {
		in, out := &in.TosLink, &out.TosLink
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPrivacyPolicyObservation.
func (in *DefaultPrivacyPolicyObservation) DeepCopy() *DefaultPrivacyPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultPrivacyPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPrivacyPolicyParameters) DeepCopyInto(out *DefaultPrivacyPolicyParameters) {
	*out = *in
	if in.HelpLink != nil {
		in, out := &in.HelpLink, &out.HelpLink
		*out = new(string)
		**out = **in
	}
	if in.PrivacyLink != nil {
		in, out := &in.PrivacyLink, &out.PrivacyLink
		*out = new(string)
		**out = **in
	}
	if in.SupportEmail != nil {
		in, out := &in.SupportEmail, &out.SupportEmail
		*out = new(string)
		**out = **in
	}
	if in.TosLink != nil {
		in, out := &in.TosLink, &out.TosLink
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPrivacyPolicyParameters.
func (in *DefaultPrivacyPolicyParameters) DeepCopy() *DefaultPrivacyPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultPrivacyPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPrivacyPolicySpec) DeepCopyInto(out *DefaultPrivacyPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPrivacyPolicySpec.
func (in *DefaultPrivacyPolicySpec) DeepCopy() *DefaultPrivacyPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DefaultPrivacyPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPrivacyPolicyStatus) DeepCopyInto(out *DefaultPrivacyPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPrivacyPolicyStatus.
func (in *DefaultPrivacyPolicyStatus) DeepCopy() *DefaultPrivacyPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DefaultPrivacyPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Domain) DeepCopyInto(out *Domain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Domain.
func (in *Domain) DeepCopy() *Domain {
	if in == nil {
		return nil
	}
	out := new(Domain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Domain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainInitParameters) DeepCopyInto(out *DomainInitParameters) {
	*out = *in
	if in.IsPrimary != nil {
		in, out := &in.IsPrimary, &out.IsPrimary
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.OrgIDRef != nil {
		in, out := &in.OrgIDRef, &out.OrgIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgIDSelector != nil {
		in, out := &in.OrgIDSelector, &out.OrgIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainInitParameters.
func (in *DomainInitParameters) DeepCopy() *DomainInitParameters {
	if in == nil {
		return nil
	}
	out := new(DomainInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainList) DeepCopyInto(out *DomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Domain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainList.
func (in *DomainList) DeepCopy() *DomainList {
	if in == nil {
		return nil
	}
	out := new(DomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainObservation) DeepCopyInto(out *DomainObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsPrimary != nil {
		in, out := &in.IsPrimary, &out.IsPrimary
		*out = new(bool)
		**out = **in
	}
	if in.IsVerified != nil {
		in, out := &in.IsVerified, &out.IsVerified
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.ValidationType != nil {
		in, out := &in.ValidationType, &out.ValidationType
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainObservation.
func (in *DomainObservation) DeepCopy() *DomainObservation {
	if in == nil {
		return nil
	}
	out := new(DomainObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainParameters) DeepCopyInto(out *DomainParameters) {
	*out = *in
	if in.IsPrimary != nil {
		in, out := &in.IsPrimary, &out.IsPrimary
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.OrgIDRef != nil {
		in, out := &in.OrgIDRef, &out.OrgIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgIDSelector != nil {
		in, out := &in.OrgIDSelector, &out.OrgIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainParameters.
func (in *DomainParameters) DeepCopy() *DomainParameters {
	if in == nil {
		return nil
	}
	out := new(DomainParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainSpec) DeepCopyInto(out *DomainSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainSpec.
func (in *DomainSpec) DeepCopy() *DomainSpec {
	if in == nil {
		return nil
	}
	out := new(DomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainStatus) DeepCopyInto(out *DomainStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainStatus.
func (in *DomainStatus) DeepCopy() *DomainStatus {
	if in == nil {
		return nil
	}
	out := new(DomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Org) DeepCopyInto(out *Org) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Org.
func (in *Org) DeepCopy() *Org {
	if in == nil {
		return nil
	}
	out := new(Org)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Org) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgInitParameters) DeepCopyInto(out *OrgInitParameters) {
	*out = *in
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgInitParameters.
func (in *OrgInitParameters) DeepCopy() *OrgInitParameters {
	if in == nil {
		return nil
	}
	out := new(OrgInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgList) DeepCopyInto(out *OrgList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Org, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgList.
func (in *OrgList) DeepCopy() *OrgList {
	if in == nil {
		return nil
	}
	out := new(OrgList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrgList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMember) DeepCopyInto(out *OrgMember) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMember.
func (in *OrgMember) DeepCopy() *OrgMember {
	if in == nil {
		return nil
	}
	out := new(OrgMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrgMember) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMemberInitParameters) DeepCopyInto(out *OrgMemberInitParameters) {
	*out = *in
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.OrgIDRef != nil {
		in, out := &in.OrgIDRef, &out.OrgIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgIDSelector != nil {
		in, out := &in.OrgIDSelector, &out.OrgIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMemberInitParameters.
func (in *OrgMemberInitParameters) DeepCopy() *OrgMemberInitParameters {
	if in == nil {
		return nil
	}
	out := new(OrgMemberInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMemberList) DeepCopyInto(out *OrgMemberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OrgMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMemberList.
func (in *OrgMemberList) DeepCopy() *OrgMemberList {
	if in == nil {
		return nil
	}
	out := new(OrgMemberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrgMemberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMemberObservation) DeepCopyInto(out *OrgMemberObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMemberObservation.
func (in *OrgMemberObservation) DeepCopy() *OrgMemberObservation {
	if in == nil {
		return nil
	}
	out := new(OrgMemberObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMemberParameters) DeepCopyInto(out *OrgMemberParameters) {
	*out = *in
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.OrgIDRef != nil {
		in, out := &in.OrgIDRef, &out.OrgIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgIDSelector != nil {
		in, out := &in.OrgIDSelector, &out.OrgIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMemberParameters.
func (in *OrgMemberParameters) DeepCopy() *OrgMemberParameters {
	if in == nil {
		return nil
	}
	out := new(OrgMemberParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMemberSpec) DeepCopyInto(out *OrgMemberSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMemberSpec.
func (in *OrgMemberSpec) DeepCopy() *OrgMemberSpec {
	if in == nil {
		return nil
	}
	out := new(OrgMemberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMemberStatus) DeepCopyInto(out *OrgMemberStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMemberStatus.
func (in *OrgMemberStatus) DeepCopy() *OrgMemberStatus {
	if in == nil {
		return nil
	}
	out := new(OrgMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMetadata) DeepCopyInto(out *OrgMetadata) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMetadata.
func (in *OrgMetadata) DeepCopy() *OrgMetadata {
	if in == nil {
		return nil
	}
	out := new(OrgMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrgMetadata) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMetadataInitParameters) DeepCopyInto(out *OrgMetadataInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.OrgIDRef != nil {
		in, out := &in.OrgIDRef, &out.OrgIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgIDSelector != nil {
		in, out := &in.OrgIDSelector, &out.OrgIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMetadataInitParameters.
func (in *OrgMetadataInitParameters) DeepCopy() *OrgMetadataInitParameters {
	if in == nil {
		return nil
	}
	out := new(OrgMetadataInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMetadataList) DeepCopyInto(out *OrgMetadataList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OrgMetadata, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMetadataList.
func (in *OrgMetadataList) DeepCopy() *OrgMetadataList {
	if in == nil {
		return nil
	}
	out := new(OrgMetadataList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrgMetadataList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMetadataObservation) DeepCopyInto(out *OrgMetadataObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMetadataObservation.
func (in *OrgMetadataObservation) DeepCopy() *OrgMetadataObservation {
	if in == nil {
		return nil
	}
	out := new(OrgMetadataObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMetadataParameters) DeepCopyInto(out *OrgMetadataParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.OrgIDRef != nil {
		in, out := &in.OrgIDRef, &out.OrgIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgIDSelector != nil {
		in, out := &in.OrgIDSelector, &out.OrgIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMetadataParameters.
func (in *OrgMetadataParameters) DeepCopy() *OrgMetadataParameters {
	if in == nil {
		return nil
	}
	out := new(OrgMetadataParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMetadataSpec) DeepCopyInto(out *OrgMetadataSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMetadataSpec.
func (in *OrgMetadataSpec) DeepCopy() *OrgMetadataSpec {
	if in == nil {
		return nil
	}
	out := new(OrgMetadataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgMetadataStatus) DeepCopyInto(out *OrgMetadataStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgMetadataStatus.
func (in *OrgMetadataStatus) DeepCopy() *OrgMetadataStatus {
	if in == nil {
		return nil
	}
	out := new(OrgMetadataStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgObservation) DeepCopyInto(out *OrgObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PrimaryDomain != nil {
		in, out := &in.PrimaryDomain, &out.PrimaryDomain
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgObservation.
func (in *OrgObservation) DeepCopy() *OrgObservation {
	if in == nil {
		return nil
	}
	out := new(OrgObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgParameters) DeepCopyInto(out *OrgParameters) {
	*out = *in
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgParameters.
func (in *OrgParameters) DeepCopy() *OrgParameters {
	if in == nil {
		return nil
	}
	out := new(OrgParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgSpec) DeepCopyInto(out *OrgSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgSpec.
func (in *OrgSpec) DeepCopy() *OrgSpec {
	if in == nil {
		return nil
	}
	out := new(OrgSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgStatus) DeepCopyInto(out *OrgStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgStatus.
func (in *OrgStatus) DeepCopy() *OrgStatus {
	if in == nil {
		return nil
	}
	out := new(OrgStatus)
	in.DeepCopyInto(out)
	return out
}
