apiVersion: org.zitadel.crossplane.io/v1alpha1
kind: OrgMetadata
metadata:
  annotations:
    meta.upbound.io/example-id: org/v1alpha1/orgmetadata
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    key: a_key
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    value: a_value
