//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainClaimedMessageText) DeepCopyInto(out *DomainClaimedMessageText) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainClaimedMessageText.
func (in *DomainClaimedMessageText) DeepCopy() *DomainClaimedMessageText {
	if in == nil {
		return nil
	}
	out := new(DomainClaimedMessageText)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DomainClaimedMessageText) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainClaimedMessageTextInitParameters) DeepCopyInto(out *DomainClaimedMessageTextInitParameters) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainClaimedMessageTextInitParameters.
func (in *DomainClaimedMessageTextInitParameters) DeepCopy() *DomainClaimedMessageTextInitParameters {
	if in == nil {
		return nil
	}
	out := new(DomainClaimedMessageTextInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainClaimedMessageTextList) DeepCopyInto(out *DomainClaimedMessageTextList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DomainClaimedMessageText, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainClaimedMessageTextList.
func (in *DomainClaimedMessageTextList) DeepCopy() *DomainClaimedMessageTextList {
	if in == nil {
		return nil
	}
	out := new(DomainClaimedMessageTextList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DomainClaimedMessageTextList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainClaimedMessageTextObservation) DeepCopyInto(out *DomainClaimedMessageTextObservation) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainClaimedMessageTextObservation.
func (in *DomainClaimedMessageTextObservation) DeepCopy() *DomainClaimedMessageTextObservation {
	if in == nil {
		return nil
	}
	out := new(DomainClaimedMessageTextObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainClaimedMessageTextParameters) DeepCopyInto(out *DomainClaimedMessageTextParameters) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainClaimedMessageTextParameters.
func (in *DomainClaimedMessageTextParameters) DeepCopy() *DomainClaimedMessageTextParameters {
	if in == nil {
		return nil
	}
	out := new(DomainClaimedMessageTextParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainClaimedMessageTextSpec) DeepCopyInto(out *DomainClaimedMessageTextSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainClaimedMessageTextSpec.
func (in *DomainClaimedMessageTextSpec) DeepCopy() *DomainClaimedMessageTextSpec {
	if in == nil {
		return nil
	}
	out := new(DomainClaimedMessageTextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainClaimedMessageTextStatus) DeepCopyInto(out *DomainClaimedMessageTextStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainClaimedMessageTextStatus.
func (in *DomainClaimedMessageTextStatus) DeepCopy() *DomainClaimedMessageTextStatus {
	if in == nil {
		return nil
	}
	out := new(DomainClaimedMessageTextStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitMessageText) DeepCopyInto(out *InitMessageText) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitMessageText.
func (in *InitMessageText) DeepCopy() *InitMessageText {
	if in == nil {
		return nil
	}
	out := new(InitMessageText)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InitMessageText) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitMessageTextInitParameters) DeepCopyInto(out *InitMessageTextInitParameters) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitMessageTextInitParameters.
func (in *InitMessageTextInitParameters) DeepCopy() *InitMessageTextInitParameters {
	if in == nil {
		return nil
	}
	out := new(InitMessageTextInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitMessageTextList) DeepCopyInto(out *InitMessageTextList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InitMessageText, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitMessageTextList.
func (in *InitMessageTextList) DeepCopy() *InitMessageTextList {
	if in == nil {
		return nil
	}
	out := new(InitMessageTextList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InitMessageTextList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitMessageTextObservation) DeepCopyInto(out *InitMessageTextObservation) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitMessageTextObservation.
func (in *InitMessageTextObservation) DeepCopy() *InitMessageTextObservation {
	if in == nil {
		return nil
	}
	out := new(InitMessageTextObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitMessageTextParameters) DeepCopyInto(out *InitMessageTextParameters) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitMessageTextParameters.
func (in *InitMessageTextParameters) DeepCopy() *InitMessageTextParameters {
	if in == nil {
		return nil
	}
	out := new(InitMessageTextParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitMessageTextSpec) DeepCopyInto(out *InitMessageTextSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitMessageTextSpec.
func (in *InitMessageTextSpec) DeepCopy() *InitMessageTextSpec {
	if in == nil {
		return nil
	}
	out := new(InitMessageTextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitMessageTextStatus) DeepCopyInto(out *InitMessageTextStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitMessageTextStatus.
func (in *InitMessageTextStatus) DeepCopy() *InitMessageTextStatus {
	if in == nil {
		return nil
	}
	out := new(InitMessageTextStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifySMSOtpMessageText) DeepCopyInto(out *VerifySMSOtpMessageText) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifySMSOtpMessageText.
func (in *VerifySMSOtpMessageText) DeepCopy() *VerifySMSOtpMessageText {
	if in == nil {
		return nil
	}
	out := new(VerifySMSOtpMessageText)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerifySMSOtpMessageText) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifySMSOtpMessageTextInitParameters) DeepCopyInto(out *VerifySMSOtpMessageTextInitParameters) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifySMSOtpMessageTextInitParameters.
func (in *VerifySMSOtpMessageTextInitParameters) DeepCopy() *VerifySMSOtpMessageTextInitParameters {
	if in == nil {
		return nil
	}
	out := new(VerifySMSOtpMessageTextInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifySMSOtpMessageTextList) DeepCopyInto(out *VerifySMSOtpMessageTextList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VerifySMSOtpMessageText, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifySMSOtpMessageTextList.
func (in *VerifySMSOtpMessageTextList) DeepCopy() *VerifySMSOtpMessageTextList {
	if in == nil {
		return nil
	}
	out := new(VerifySMSOtpMessageTextList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerifySMSOtpMessageTextList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifySMSOtpMessageTextObservation) DeepCopyInto(out *VerifySMSOtpMessageTextObservation) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifySMSOtpMessageTextObservation.
func (in *VerifySMSOtpMessageTextObservation) DeepCopy() *VerifySMSOtpMessageTextObservation {
	if in == nil {
		return nil
	}
	out := new(VerifySMSOtpMessageTextObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifySMSOtpMessageTextParameters) DeepCopyInto(out *VerifySMSOtpMessageTextParameters) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifySMSOtpMessageTextParameters.
func (in *VerifySMSOtpMessageTextParameters) DeepCopy() *VerifySMSOtpMessageTextParameters {
	if in == nil {
		return nil
	}
	out := new(VerifySMSOtpMessageTextParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifySMSOtpMessageTextSpec) DeepCopyInto(out *VerifySMSOtpMessageTextSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifySMSOtpMessageTextSpec.
func (in *VerifySMSOtpMessageTextSpec) DeepCopy() *VerifySMSOtpMessageTextSpec {
	if in == nil {
		return nil
	}
	out := new(VerifySMSOtpMessageTextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifySMSOtpMessageTextStatus) DeepCopyInto(out *VerifySMSOtpMessageTextStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifySMSOtpMessageTextStatus.
func (in *VerifySMSOtpMessageTextStatus) DeepCopy() *VerifySMSOtpMessageTextStatus {
	if in == nil {
		return nil
	}
	out := new(VerifySMSOtpMessageTextStatus)
	in.DeepCopyInto(out)
	return out
}
