apiVersion: notif.zitadel.crossplane.io/v1alpha1
kind: PasswordResetMessageText
metadata:
  annotations:
    meta.upbound.io/example-id: notif/v1alpha1/passwordresetmessagetext
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    hasLowercase: true
    hasNumber: true
    hasSymbol: true
    hasUppercase: true
    minLength: "8"
    orgId: ${data.zitadel_org.default.id}
