// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *DefaultPasswordChangeMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DefaultPasswordComplexityPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DefaultPasswordLessRegistrationMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DefaultPasswordResetMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DefaultVerifyEmailMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DefaultVerifyEmailOtpMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DefaultVerifyPhoneMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DomainClaimedMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InitMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PasswordChangeMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PasswordLessRegistrationMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PasswordResetMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SmsProviderTwilio) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SmtpConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VerifyEmailMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VerifyEmailOtpMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VerifyphoneMessageText) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VerifysmsOtpMessageText) Hub() {}
